version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/myapp
permissions:
  - object: /var/www/myapp
    pattern: "**/*"
    owner: ec2-user
    group: ec2-user
    mode: 755
hooks:
  BeforeInstall:
    - location: scripts/install_mongodb.sh
      timeout: 60
      runas: root
    - location: scripts/install_node.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/server_setup.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: scripts/run_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 60
      runas: root