name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Upload to S3
        run: |
          aws s3 cp acebook-node-template-team-evergreen/ s3://team-evergreen
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Trigger CodeDeploy Deployment
        run: |
          aws deploy create-deployment --application-name team-evergreen-codedeploy --s3-location bucket=team-evergreen,key=acebook-node-template-team-evergreen.zip --deployment-group-name team-evergreen --region your-region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
