name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
          --application-name team-evergreen-codedeploy \
          --deployment-group-name team-evergreen \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --github-location repository=LloydDunn/acebook-node-template-team-evergreen,commitId=47134a6a348685a40e89ae8c2cc10753c61f5d61 \
          --region us-west-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          