name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js version 20
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Add more steps as needed for building, testing, etc.

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: continuous-integration
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: MySessionName

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name team-evergreen-codedeploy \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }} \
            --deployment-group-name evergreen-production \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --region eu-west-2
