name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]  # Change to Node.js version 18
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:test
          wait-on: 'http://localhost:3030'
          config-file: 'cypress.config.js'

      - run: npm run lint

      - run: npm run test:unit

      # Step to zip the application
      - name: Zip
        run: zip -r app.zip .
      
      # Step to upload the zip application
      - name: Upload
        run: |
          aws s3 cp app.zip s3://team-evergreen/app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-2

  continuous-deployment:
    runs-on: ubuntu-latest
    needs: continuous-integration
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS Credentials and Set Region
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy with CodeDeploy
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name team-evergreen-codedeploy \
            --s3-location bucket=team-evergreen,key=app.zip,bundleType=zip \
            --deployment-group-name evergreen-production \
            --deployment-config-name CodeDeployDefault.OneAtATime \